apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sweetrpg-admin

resources:
  - ../../base
  - configmaps.yaml
  - ingress.yaml
  - middlewares/errors.yaml
  - middlewares/strip.yaml
  - pod-monitor.yaml
  - secrets/admin.yaml
  - secrets/auth.yaml
  - secrets/shared.yaml
  - secrets/users.yaml

labels:
  - pairs:
      app.kubernetes.io/name: admin-web
      app.kubernetes.io/version: v1
      app.kubernetes.io/component: web
      app.kubernetes.io/part-of: admin
      com.sweetrpg/env: dev

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: admin-web
    newName: ghcr.io/sweetrpg/admin-web
    newTag: latest
